# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

 #shared:
  # stripe_api_key: sk_test_BGrIU7HHJMD02CQiipPv7A40
  # stripe_publishable_key: pk_test_3weLisxYwQ1v8CPH4Db17fyG
  # secret_key_base: e8fa767a04bed70545943067a5a081d168d77595ef23acb26b9e49fca9bab4f052c5491998a6ec91216157abd3bba5db04a4716dbe81e613c4471d7524b1ba8d

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8fa767a04bed70545943067a5a081d168d77595ef23acb26b9e49fca9bab4f052c5491998a6ec91216157abd3bba5db04a4716dbe81e613c4471d7524b1ba8d

test:
  secret_key_base: 3547840609ca8aee56a4309c9508bdfbc1edeb91e4d2a34ab586a3a87786ea0aa54714a423824d1509a0affa7e85ac2a4e047ddf027c14c2807f46c80300f8e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
